### ISSUE TITLE
Dim level (switch only)

### ISSUE THREAD

**Issue by froh2018** [timkouters/nl.timkouters.domitech#5]
Dear Tim,

Thank you very much for creating the domitech app. It works fine with my Homey and domitech led bulbs (4 pieces).
I've got a question though: Is it possible to make parameter 1 (Dim level SWITCH ONLY ) available for change (possible values 0 or 1) via Homey, or is that already possible via expert settings? If so, I do not know how to accomplish that.
I wish to avoid full brightness when my bulbs are turned on by my guests who are not familair with home automation.
Text from the domitech manual: 
<img width="498" alt="parameter 1" src="https://user-images.githubusercontent.com/46421843/50738364-51396b80-11d3-11e9-8be4-78ff5ec726de.PNG">
Thank you very much in advance!

Kees Huigen

**Comment by timkouters** [comment]
Hi,

I was not able to fix it on byte-level since I'm using Athom's Z-Wave-MeshDriver where I cannot access the byte-level payloads of the Z-wave messages.
However I managed to do it with a work-around.

When turning on the lamp with a light-switch the brightness will be put back at the last dim-level known.
What you will see is that the lamp will power-on on full brightness and after a second it will dim again to the last known dim-level.
The option can be switched in the advanced settings of the device and is default on.

Fixed in b0c3e865e2a9d1869b21c901171b894a58acbf75.
App is posted and will be published as version 1.0.8 after approval of Athom.
